
import java.awt.HeadlessException;
import java.io.IOException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author codearta
 */
public class JFrameAplikasiPenghitungKata extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameAplikasiPenghitungKata.class.getName());

    /**
     * Creates new form JFrameAplikasiPenghitungKata
     */
    public JFrameAplikasiPenghitungKata() {
        initComponents();
        txtInput.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) { hitung(); }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) { hitung(); }
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) { hitung(); }

            public void hitung() {
                String teks = txtInput.getText().trim();
                int jumlahKarakter = teks.length();
                String[] kataArray = teks.isEmpty() ? new String[0] : teks.split("\\s+");
                int jumlahKata = kataArray.length;
                String[] kalimatArray = teks.split("[.!?]+");
                int jumlahKalimat = (teks.isEmpty()) ? 0 : kalimatArray.length;
                String[] paragrafArray = teks.split("(\\r?\\n){2,}");
                int jumlahParagraf = (teks.isEmpty()) ? 0 : paragrafArray.length;

                lblKataHasil.setText(String.valueOf(jumlahKata));
                lblKarakterHasil.setText(String.valueOf(jumlahKarakter));
                lblKalimatHasil.setText(String.valueOf(jumlahKalimat));
                lblParagrafHasil.setText(String.valueOf(jumlahParagraf));
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblKataHasil = new javax.swing.JLabel();
        lblKarakterHasil = new javax.swing.JLabel();
        lblKalimatHasil = new javax.swing.JLabel();
        lblParagrafHasil = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblHasilCariValue = new javax.swing.JLabel();
        scrollInput = new javax.swing.JScrollPane();
        txtInput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("APLIKASI PENGHITUNG KATA");

        jLabel2.setText("Masukkan Text Disini ");

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan Ke File");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jLabel3.setText("Jumlah Kata");

        jLabel4.setText("Jumlah Karakter");

        jLabel5.setText("Jumlah Kalimat");

        jLabel6.setText("Jumlah Paragraf");

        jLabel7.setText(":");

        jLabel8.setText(":");

        jLabel9.setText(":");

        jLabel10.setText(":");

        lblKataHasil.setText("-");

        lblKarakterHasil.setText("-");

        lblKalimatHasil.setText("-");

        lblParagrafHasil.setText("-");

        btnCari.setText("Cari Kata");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jLabel15.setText("Masukkan Kata Yang Dicari");

        jLabel16.setText("Hasil Pencarian");

        jLabel17.setText(":");

        lblHasilCariValue.setText("-");

        txtInput.setColumns(20);
        txtInput.setLineWrap(true);
        txtInput.setRows(5);
        txtInput.setWrapStyleWord(true);
        scrollInput.setViewportView(txtInput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(lblParagrafHasil))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(lblKalimatHasil))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(lblKarakterHasil))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(lblKataHasil))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(lblHasilCariValue))
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHitung)
                        .addGap(18, 18, 18)
                        .addComponent(btnSimpan))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnCari)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(275, 275, 275)))
                    .addComponent(scrollInput))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollInput, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHitung)
                    .addComponent(btnSimpan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(lblKataHasil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(lblKarakterHasil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(lblKalimatHasil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(lblParagrafHasil))
                .addGap(32, 32, 32)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(lblHasilCariValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        String teks = txtInput.getText().trim();

        // Hitung karakter
        int jumlahKarakter = teks.length();

        // Hitung kata (pakai spasi)
        String[] kataArray = teks.isEmpty() ? new String[0] : teks.split("\\s+");
        int jumlahKata = kataArray.length;

        // Hitung kalimat (berdasarkan ., !, ?)
        String[] kalimatArray = teks.split("[.!?]+");
        int jumlahKalimat = (teks.isEmpty()) ? 0 : kalimatArray.length;

        // Hitung paragraf (berdasarkan enter 2x)
        String[] paragrafArray = teks.split("(\\r?\\n){2,}");
        int jumlahParagraf = (teks.isEmpty()) ? 0 : paragrafArray.length;

        // Tampilkan hasil ke label
        lblKataHasil.setText(String.valueOf(jumlahKata));
        lblKarakterHasil.setText(String.valueOf(jumlahKarakter));
        lblKalimatHasil.setText(String.valueOf(jumlahKalimat));
        lblParagrafHasil.setText(String.valueOf(jumlahParagraf));
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        String teks = txtInput.getText().toLowerCase();
        String kataCari = txtCari.getText().toLowerCase().trim();

        if (kataCari.isEmpty()) {
            lblHasilCariValue.setText("Masukkan kata dulu!");
            return;
        }

        int count = 0;
        for (String kata : teks.split("\\s+")) {
            if (kata.equals(kataCari)) count++;
        }

        lblHasilCariValue.setText("<html>Kata <b>\"" + kataCari + "\"</b> muncul " + count + " kali</html>");

    }//GEN-LAST:event_btnCariActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
       try {
            // Buka dialog pilih lokasi penyimpanan
            javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
            fileChooser.setDialogTitle("Pilih Lokasi dan Nama File");

            // Set nama default file
            fileChooser.setSelectedFile(new java.io.File("hasil_penghitung_kata_" + System.currentTimeMillis() + ".txt"));

            int userSelection = fileChooser.showSaveDialog(this);

            if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
                java.io.File fileToSave = fileChooser.getSelectedFile();

                // Tulis hasil ke file yang dipilih user
                java.io.BufferedWriter bw = new java.io.BufferedWriter(
                    new java.io.FileWriter(fileToSave)
                );

                bw.write("=== HASIL PENGHITUNG KATA ===\n");
                bw.write("Jumlah Kata: " + lblKataHasil.getText() + "\n");
                bw.write("Jumlah Karakter: " + lblKarakterHasil.getText() + "\n");
                bw.write("Jumlah Kalimat: " + lblKalimatHasil.getText() + "\n");
                bw.write("Jumlah Paragraf: " + lblParagrafHasil.getText() + "\n");
                bw.close();

                javax.swing.JOptionPane.showMessageDialog(this,
                    "Hasil berhasil disimpan ke:\n" + fileToSave.getAbsolutePath());
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Penyimpanan dibatalkan oleh pengguna.");
            }
        } catch (HeadlessException | IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Gagal menyimpan file: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameAplikasiPenghitungKata().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblHasilCariValue;
    private javax.swing.JLabel lblKalimatHasil;
    private javax.swing.JLabel lblKarakterHasil;
    private javax.swing.JLabel lblKataHasil;
    private javax.swing.JLabel lblParagrafHasil;
    private javax.swing.JScrollPane scrollInput;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextArea txtInput;
    // End of variables declaration//GEN-END:variables
}
